_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_dialogs: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  all_games: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facets: 0
  facets_block: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  football_archive: 0
  gin_login: 0
  help: 0
  history: 0
  image: 0
  inline_form_errors: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rate: 0
  search_api: 0
  search_api_db: 0
  select2: 0
  select2_facets: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  user: 0
  views_ui: 0
  votingapi: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
  stable9: 0
  football_theme: 0
profile: standard
